name: Push

on:
  push:
    branches:
      - '**'

jobs:
  compilemanifest:
    name: Post Push
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Build manifest